apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: trs-secret-store
  namespace: poc
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: trs-service-account