apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: trs-external-secret
  namespace: poc
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: trs-secret-store
    kind: SecretStore
  target:
    name: trs-secret
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: trs/poc/credentials
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: trs/poc/credentials
        property: AWS_SECRET_ACCESS_KEY