apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: trs-external-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecret.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: {{ .Values.externalSecret.awsSecretPath }}
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: {{ .Values.externalSecret.awsSecretPath }}
        property: AWS_SECRET_ACCESS_KEY